#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    leading_diamond = '╭─'
    background = '#E5E9F0'
    foreground = '#4C566A'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = ' </>{{ .Path }} '
    background = '#81A1C1'
    foreground = '#2E3440'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}#D08770{{ end }}', 
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#EBCB8B{{ end }}', 
      '{{ if gt .Ahead 0 }}#B48EAD{{ end }}',
      '{{ if gt .Behind 0 }}#B48EAD{{ end }}'
      ]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }} {{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
   
    background = '#A3BE8C'
    foreground = '#2E3440'
    Text = ''
    Duration = 0
    NameLength = 0
    
    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

    [properties.mapped_branches]
      "feature/*" = "✦"
      "bug/*" = "✧"
      "release*" = "⊜"
      "master" = "◉"
      "hotfix/*" = "✢"

    [blocks.segments.properties.status_formats]
      Added = "+%d"
      Modified = "~%d"
      Deleted = "-%d"
      Untracked = "?%d"
      Renamed = "»%d"

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ .FormattedMs }} '
    background = '#B48EAD'
    foreground = '#2E3440'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      always_enabled = false
      threshold = 10000
      

[[blocks]]
  type = 'prompt'
  alignment = 'right'

[[blocks.segments]]
    type = 'status'
    style = 'powerline'
    background_templates = ['{{ if gt .Code 0 }}#BF616A{{ end }}']
    powerline_symbol = ''
    invert_powerline = true
    template = ' {{ if gt .Code 0 }} {{ else }} {{ end }}'
    background = '#EBCB8B'
    foreground = '#2E3440'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      always_enabled = true

[[blocks.segments]]
    type = 'python'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    template = ' {{ if .Venv }}({{ .Venv }}){{ end }} '
    background = '#A3BE8C'
    foreground = '#2E3440'
  
  [blocks.segments.properties]
    fetch_virtual_env = true

[[blocks.segments]]
    type = 'aws'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    template = ' {{ .Profile }} '
    background = '#D08770'
    foreground = '#2E3440'

  [blocks.segments.properties]
      display_default = true
      condition = """[ -f ~/.aws/credentials ] || [ -f ~/.aws/config ] || [ -n "$AWS_ACCESS_KEY_ID" ] || [ -f serverless.yml ] || [ -f template.yaml ] || [ -f template.json ]"""

[[blocks.segments]]
    type = 'terraform'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    template = ' {{ .WorkspaceName }}{{ if .Version }} {{ .Version }}{{ end }} '
    background = '#D08770'
    foreground = '#2E3440'

  [blocks.segments.properties]
      display_default = true
      fetch_version = true 
      condition = '''
          [[ -f "*.tf" ]] || 
          [[ -f "*.tfvars" ]] || 
          [[ -f ".terraform.lock.hcl" ]] || 
          [[ -d ".terraform" ]]
          '''


[[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    trailing_diamond = ''
    template = ' {{ .CurrentDate | date "15:04"  }} '
    background = '#81A1C1'
    foreground = '#2E3440'
    Text = ''
    Duration = 0
    NameLength = 0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '╰─'
    background = ''
    foreground = '#ECEFF4'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']
    template = '<#B48EAD>❯</><#A3BE8C>❯</><#EBCB8B>❯</> '
    background = ''
    foreground = '#8FBCBB'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      always_enabled = true
